# Generated by Django 3.2.15 on 2022-12-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteSearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wasteinfo',
            old_name='BaO_2',
            new_name='P_BaO',
        ),
        migrations.RenameField(
            model_name='wasteinfo',
            old_name='Cl_2',
            new_name='P_Cl',
        ),
        migrations.RenameField(
            model_name='wasteinfo',
            old_name='F_2',
            new_name='P_F',
        ),
        migrations.RenameField(
            model_name='wasteinfo',
            old_name='S_2',
            new_name='P_S',
        ),
        migrations.RemoveField(
            model_name='wasteinfo',
            name='AlOH3',
        ),
        migrations.RemoveField(
            model_name='wasteinfo',
            name='NaNO3',
        ),
        migrations.RemoveField(
            model_name='wasteinfo',
            name='_2氯烟酰胺_2',
        ),
        migrations.RemoveField(
            model_name='wasteinfo',
            name='丁草胺_2',
        ),
        migrations.RemoveField(
            model_name='wasteinfo',
            name='二氯甲烷_2',
        ),
        migrations.RemoveField(
            model_name='wasteinfo',
            name='甲酸_2',
        ),
        migrations.AddField(
            model_name='wasteinfo',
            name='L_F',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='L F'),
        ),
        migrations.AddField(
            model_name='wasteinfo',
            name='NaOH',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='NaOH'),
        ),
        migrations.AddField(
            model_name='wasteinfo',
            name='表观形貌关键词',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='表观形貌关键词'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='CN',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='CN'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='L_Ba',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='L Ba'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='L_Ca',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='L Ca'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='L_Cr',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='L Cr'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='L_Fe',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='L Fe'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='L_Mg',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='L Mg'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='NH4Cl',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='NH4Cl(%)'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='NaCl',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='NaCl(%)'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='T_Al',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='T Al'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='T_Al3',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='T Al3+'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='T_B',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='T B'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='T_Ca',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='T Ca'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='T_Cr',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='T Cr'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='T_F',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='T F'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='T_K',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='T K'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='T_Mg',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='T Mg'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='T_Na',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='T Na'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='T_SO42',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='T SO42-'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='_24D',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='2,4-D'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='_24二氯苯氧乙酸钠',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='2,4-二氯苯氧乙酸钠'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='_24二氯酚',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='2,4-二氯酚'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='_25二氯苯酚',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='2,5-二氯苯酚'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='三唑磷',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='三唑磷'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='代森锰',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='代森锰'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='双甘膦',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='双甘膦'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='增甘膦',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='增甘膦'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='多菌灵',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='多菌灵'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='烟嘧磺胺',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='烟嘧磺胺'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='烟嘧磺酰氯',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='烟嘧磺酰氯'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='百草枯',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='百草枯'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='羟基乙酸',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='羟基乙酸'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='苯氧乙酸',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='苯氧乙酸'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='草甘膦',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='草甘膦'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='莠去津',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='莠去津'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='西玛津',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='西玛津'),
        ),
    ]
