# Generated by Django 3.2.15 on 2022-12-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasteSearch', '0002_auto_20221224_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasteinfo',
            name='L_Mn',
        ),
    ]
