# Generated by Django 3.2.15 on 2022-12-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteSearch', '0003_remove_wasteinfo_l_mn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wasteinfo',
            old_name='_1苯基氨基脲',
            new_name='T_1苯基氨基脲',
        ),
        migrations.RenameField(
            model_name='wasteinfo',
            old_name='_24D',
            new_name='T_24D',
        ),
        migrations.RenameField(
            model_name='wasteinfo',
            old_name='_24二氯苯氧乙酸钠',
            new_name='T_24二氯苯氧乙酸钠',
        ),
        migrations.RenameField(
            model_name='wasteinfo',
            old_name='_24二氯酚',
            new_name='T_24二氯酚',
        ),
        migrations.RenameField(
            model_name='wasteinfo',
            old_name='_25二氯苯胺',
            new_name='T_25二氯苯胺',
        ),
        migrations.RenameField(
            model_name='wasteinfo',
            old_name='_25二氯苯酚',
            new_name='T_25二氯苯酚',
        ),
        migrations.RenameField(
            model_name='wasteinfo',
            old_name='_2氯5氯甲基吡啶',
            new_name='T_2氯5氯甲基吡啶',
        ),
        migrations.RenameField(
            model_name='wasteinfo',
            old_name='_2氯N氯甲基_N26二乙基苯基乙酰胺MRM',
            new_name='T_2氯N氯甲基_N26二乙基苯基乙酰胺MRM',
        ),
        migrations.RenameField(
            model_name='wasteinfo',
            old_name='_2氯烟酰胺',
            new_name='T_2氯烟酰胺',
        ),
        migrations.RenameField(
            model_name='wasteinfo',
            old_name='_2甲4氯酸',
            new_name='T_2甲4氯酸',
        ),
        migrations.RenameField(
            model_name='wasteinfo',
            old_name='_43甲基3甲亚基氨基苯基丁酸乙酯',
            new_name='T_43甲基3甲亚基氨基苯基丁酸乙酯',
        ),
        migrations.RenameField(
            model_name='wasteinfo',
            old_name='_4_3乙基2甲亚基氨基苯基丁酰氯',
            new_name='T_4_3乙基2甲亚基氨基苯基丁酰氯',
        ),
        migrations.RenameField(
            model_name='wasteinfo',
            old_name='_4甲基2肼基苯并骈噻唑',
            new_name='T_4甲基2肼基苯并骈噻唑',
        ),
        migrations.RenameField(
            model_name='wasteinfo',
            old_name='_OO二乙基硫代磷酰氯',
            new_name='T_OO二乙基硫代磷酰氯',
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='COD',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='COD(mg/L)'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='含水率',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='含水率(%)'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='含油率',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='含油率(%)'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='固废名称',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='固废名称'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='密度',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='密度(kg/m3)'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='烟嘧磺隆',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='烟嘧磺隆(mg/kg)'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='烧失率',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='烧失率(%)'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='热值',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='热值(KJ/kg)'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='甲醛',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='甲醛'),
        ),
        migrations.AlterField(
            model_name='wasteinfo',
            name='表观形貌稍微详细',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='表观形貌(稍微详细)'),
        ),
    ]
