# Generated by Django 4.1.3 on 2023-01-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wasteSearch", "0004_auto_20221227_1101"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wasteinfo",
            name="NH4Cl",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="NH4Cl"
            ),
        ),
        migrations.AlterField(
            model_name="wasteinfo",
            name="NaCl",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="NaCl"
            ),
        ),
    ]
