# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models

class WasteInfo(models.Model):
    dataId = models.IntegerField(primary_key=True, verbose_name="序号")
    废物类别 = models.CharField(verbose_name="废物类别", max_length=64, blank=True, null=True)
    行业分类 = models.CharField(verbose_name="行业分类", max_length=64, blank=True, null=True)
    固废名称 = models.CharField(verbose_name="固废名称", max_length=64, blank=True, null=True)
    别名 = models.CharField(verbose_name="别名", max_length=64, blank=True, null=True)
    产生工段 = models.CharField(verbose_name="产生工段", max_length=128, blank=True, null=True)
    表观形貌稍微详细 = models.CharField(verbose_name="表观形貌(稍微详细)", max_length=64, blank=True, null=True)
    表观形貌关键词 = models.CharField(verbose_name="表观形貌关键词", max_length=64, blank=True, null=True)
    物理形态 = models.CharField(verbose_name="物理形态", max_length=64, blank=True, null=True)
    形状 = models.CharField(verbose_name="形状", max_length=64, blank=True, null=True)
    颜色 = models.CharField(verbose_name="颜色", max_length=64, blank=True, null=True)
    气味 = models.CharField(verbose_name="气味", max_length=64, blank=True, null=True)
    密度 = models.CharField(verbose_name="密度(kg/m3)", max_length=64, blank=True, null=True)
    含水率 = models.CharField(verbose_name="含水率(%)", max_length=64, blank=True, null=True)
    pH = models.CharField(verbose_name="pH", max_length=64, blank=True, null=True)
    含油率 = models.CharField(verbose_name="含油率(%)", max_length=64, blank=True, null=True)
    COD = models.CharField(verbose_name="COD(mg/L)", max_length=64, blank=True, null=True)
    热值 = models.CharField(verbose_name="热值(KJ/kg)", max_length=64, blank=True, null=True)
    烧失率 = models.CharField(verbose_name="烧失率(%)", max_length=64, blank=True, null=True)
    水分 = models.CharField(verbose_name="水分", max_length=64, blank=True, null=True)
    灰分 = models.CharField(verbose_name="灰分", max_length=64, blank=True, null=True)
    挥发分 = models.CharField(verbose_name="挥发分", max_length=64, blank=True, null=True)
    固定碳 = models.CharField(verbose_name="固定碳", max_length=64, blank=True, null=True)
    C = models.CharField(verbose_name="C", max_length=32, blank=True, null=True)
    H = models.CharField(verbose_name="H", max_length=32, blank=True, null=True)
    N = models.CharField(verbose_name="N", max_length=32, blank=True, null=True)
    O = models.CharField(verbose_name="O", max_length=32, blank=True, null=True)
    F = models.CharField(verbose_name="F", max_length=32, blank=True, null=True)
    Na = models.CharField(verbose_name="Na", max_length=32, blank=True, null=True)
    Mg = models.CharField(verbose_name="Mg", max_length=32, blank=True, null=True)
    Al = models.CharField(verbose_name="Al", max_length=32, blank=True, null=True)
    Si = models.CharField(verbose_name="Si	", max_length=32, blank=True, null=True)
    P = models.CharField(verbose_name="P", max_length=32, blank=True, null=True)
    S = models.CharField(verbose_name="S", max_length=32, blank=True, null=True)
    Cl = models.CharField(verbose_name="Cl", max_length=32, blank=True, null=True)
    K = models.CharField(verbose_name="K", max_length=32, blank=True, null=True)
    Ca = models.CharField(verbose_name="Ca", max_length=32, blank=True, null=True)
    Ti = models.CharField(verbose_name="Ti", max_length=32, blank=True, null=True)
    V = models.CharField(verbose_name="V", max_length=32, blank=True, null=True)
    Cr = models.CharField(verbose_name="Cr", max_length=32, blank=True, null=True)
    Mn = models.CharField(verbose_name="Mn", max_length=32, blank=True, null=True)
    Fe = models.CharField(verbose_name="Fe", max_length=32, blank=True, null=True)
    Co = models.CharField(verbose_name="Co", max_length=32, blank=True, null=True)
    Ni = models.CharField(verbose_name="Ni", max_length=32, blank=True, null=True)
    Cu = models.CharField(verbose_name="Cu	", max_length=32, blank=True, null=True)
    Zn = models.CharField(verbose_name="Zn", max_length=32, blank=True, null=True)
    As = models.CharField(verbose_name="As", max_length=32, blank=True, null=True)
    Pb = models.CharField(verbose_name="Pb", max_length=32, blank=True, null=True)
    Ag = models.CharField(verbose_name="Ag", max_length=32, blank=True, null=True)
    Bi = models.CharField(verbose_name="Bi", max_length=32, blank=True, null=True)
    Cd = models.CharField(verbose_name="Cd", max_length=32, blank=True, null=True)
    Sn = models.CharField(verbose_name="Sn", max_length=32, blank=True, null=True)
    Sb = models.CharField(verbose_name="Sb", max_length=32, blank=True, null=True)
    I = models.CharField(verbose_name="I", max_length=32, blank=True, null=True)
    Hg = models.CharField(verbose_name="Hg", max_length=32, blank=True, null=True)
    Ba = models.CharField(verbose_name="Ba", max_length=32, blank=True, null=True)
    Al2O3 = models.CharField(verbose_name="Al2O3", max_length=32, blank=True, null=True)
    MgO = models.CharField(verbose_name="MgO", max_length=32, blank=True, null=True)
    P_Cl = models.CharField(verbose_name="P Cl", max_length=32, blank=True, null=True)
    K2O = models.CharField(verbose_name="K2O", max_length=32, blank=True, null=True)
    Na2O = models.CharField(verbose_name="Na2O", max_length=32, blank=True, null=True)
    Fe2O3 = models.CharField(verbose_name="Fe2O3", max_length=32, blank=True, null=True)
    SiO2 = models.CharField(verbose_name="SiO2", max_length=32, blank=True, null=True)
    MnO = models.CharField(verbose_name="MnO", max_length=32, blank=True, null=True)
    CaO = models.CharField(verbose_name="CaO", max_length=32, blank=True, null=True)
    P_S = models.CharField(verbose_name="P S", max_length=32, blank=True, null=True)
    SO3 = models.CharField(verbose_name="SO3", max_length=32, blank=True, null=True)
    As2O3 = models.CharField(verbose_name="As2O3", max_length=32, blank=True, null=True)
    TiO2 = models.CharField(verbose_name="TiO2", max_length=32, blank=True, null=True)
    Cr2O3 = models.CharField(verbose_name="Cr2O3", max_length=32, blank=True, null=True)
    CuO = models.CharField(verbose_name="CuO", max_length=32, blank=True, null=True)
    ZnO = models.CharField(verbose_name="ZnO", max_length=32, blank=True, null=True)
    PbO = models.CharField(verbose_name="PbO", max_length=32, blank=True, null=True)
    P_F = models.CharField(verbose_name="P F", max_length=32, blank=True, null=True)
    V2O5 = models.CharField(verbose_name="V2O5", max_length=32, blank=True, null=True)
    BaO = models.CharField(verbose_name="BaO", max_length=32, blank=True, null=True)
    P2O5 = models.CharField(verbose_name="P2O5", max_length=32, blank=True, null=True)
    SnO2 = models.CharField(verbose_name="SnO2", max_length=32, blank=True, null=True)
    NiO = models.CharField(verbose_name="NiO", max_length=32, blank=True, null=True)
    NaCl = models.CharField(verbose_name="NaCl", max_length=32, blank=True, null=True)
    KCl = models.CharField(verbose_name="KCl", max_length=32, blank=True, null=True)
    MgCl2 = models.CharField(verbose_name="MgCl2", max_length=32, blank=True, null=True)
    MgOH2 = models.CharField(verbose_name="Mg(OH)2", max_length=32, blank=True, null=True)
    # AlOH3 = models.CharField(verbose_name="Al(OH)3", max_length=32, blank=True, null=True)
    AlCl3 = models.CharField(verbose_name="AlCl3", max_length=32, blank=True, null=True)
    MnCl2 = models.CharField(verbose_name="MnCl2", max_length=32, blank=True, null=True)
    NH4Cl = models.CharField(verbose_name="NH4Cl", max_length=32, blank=True, null=True)
    TiCl4 = models.CharField(verbose_name="TiCl4", max_length=32, blank=True, null=True)
    FeCl2 = models.CharField(verbose_name="FeCl2", max_length=32, blank=True, null=True)
    FeCl3 = models.CharField(verbose_name="FeCl3", max_length=32, blank=True, null=True)
    CaCl2 = models.CharField(verbose_name="CaCl2", max_length=32, blank=True, null=True)
    CaF2 = models.CharField(verbose_name="CaF2", max_length=32, blank=True, null=True)
    CaSO4 = models.CharField(verbose_name="CaSO4", max_length=32, blank=True, null=True)
    CaCO3 = models.CharField(verbose_name="CaCO3", max_length=32, blank=True, null=True)
    P_BaO = models.CharField(verbose_name="P BaO", max_length=32, blank=True, null=True)
    BaSO4 = models.CharField(verbose_name="BaSO4", max_length=32, blank=True, null=True)
    BaCO3 = models.CharField(verbose_name="BaCO3", max_length=32, blank=True, null=True)
    BaSiO3 = models.CharField(verbose_name="BaSiO3", max_length=32, blank=True, null=True)
    BaS = models.CharField(verbose_name="BaS", max_length=32, blank=True, null=True)
    NaOH = models.CharField(verbose_name="NaOH", max_length=32, blank=True, null=True)
    # NaNO3 = models.CharField(verbose_name="NaNO3", max_length=32, blank=True, null=True)
    辉铜矿 = models.CharField(verbose_name="辉铜矿", max_length=32, blank=True, null=True)
    黄铜矿 = models.CharField(verbose_name="黄铜矿", max_length=32, blank=True, null=True)
    铜铁硫化相 = models.CharField(verbose_name="铜铁硫化相", max_length=32, blank=True, null=True)
    铁橄榄石 = models.CharField(verbose_name="铁橄榄石", max_length=32, blank=True, null=True)
    磁铁矿 = models.CharField(verbose_name="磁铁矿", max_length=32, blank=True, null=True)
    钙铁辉石 = models.CharField(verbose_name="钙铁辉石", max_length=32, blank=True, null=True)
    玻璃相 = models.CharField(verbose_name="玻璃相", max_length=32, blank=True, null=True)
    石膏 = models.CharField(verbose_name="石膏", max_length=32, blank=True, null=True)
    方解石 = models.CharField(verbose_name="方解石", max_length=32, blank=True, null=True)
    石英 = models.CharField(verbose_name="石英", max_length=32, blank=True, null=True)
    砷铜矿 = models.CharField(verbose_name="砷铜矿", max_length=32, blank=True, null=True)
    皓矾 = models.CharField(verbose_name="皓矾", max_length=32, blank=True, null=True)
    六水锌矾 = models.CharField(verbose_name="六水锌矾", max_length=32, blank=True, null=True)
    氧化锑 = models.CharField(verbose_name="氧化锑", max_length=32, blank=True, null=True)
    三氧化二砷 = models.CharField(verbose_name="三氧化二砷", max_length=32, blank=True, null=True)
    五氧化二砷 = models.CharField(verbose_name="五氧化二砷", max_length=32, blank=True, null=True)
    铅绿矾 = models.CharField(verbose_name="铅绿矾", max_length=32, blank=True, null=True)
    方铅矿 = models.CharField(verbose_name="方铅矿", max_length=32, blank=True, null=True)
    铅黄 = models.CharField(verbose_name="铅黄", max_length=32, blank=True, null=True)
    铅 = models.CharField(verbose_name="铅", max_length=32, blank=True, null=True)
    密陀僧 = models.CharField(verbose_name="密陀僧", max_length=32, blank=True, null=True)
    红锌矿 = models.CharField(verbose_name="红锌矿", max_length=32, blank=True, null=True)
    闪锌矿 = models.CharField(verbose_name="闪锌矿", max_length=32, blank=True, null=True)
    锌 = models.CharField(verbose_name="锌", max_length=32, blank=True, null=True)
    纤锌矿 = models.CharField(verbose_name="纤锌矿", max_length=32, blank=True, null=True)
    冰晶石 = models.CharField(verbose_name="冰晶石", max_length=32, blank=True, null=True)
    刚玉 = models.CharField(verbose_name="刚玉", max_length=32, blank=True, null=True)
    β氧化铝 = models.CharField(verbose_name="β-氧化铝", max_length=32, blank=True, null=True)
    钾冰晶石 = models.CharField(verbose_name="钾冰晶石", max_length=32, blank=True, null=True)
    铝 = models.CharField(verbose_name="铝", max_length=32, blank=True, null=True)
    锥冰晶石 = models.CharField(verbose_name="锥冰晶石", max_length=32, blank=True, null=True)
    西蒙冰晶石 = models.CharField(verbose_name="西蒙冰晶石", max_length=32, blank=True, null=True)
    氟铝钙锂石 = models.CharField(verbose_name="氟铝钙锂石", max_length=32, blank=True, null=True)
    白砷石 = models.CharField(verbose_name="白砷石", max_length=32, blank=True, null=True)
    三水胆矾 = models.CharField(verbose_name="三水胆矾", max_length=32, blank=True, null=True)
    副雄黄 = models.CharField(verbose_name="副雄黄", max_length=32, blank=True, null=True)
    砷华 = models.CharField(verbose_name="砷华", max_length=32, blank=True, null=True)
    铅矾 = models.CharField(verbose_name="铅矾", max_length=32, blank=True, null=True)
    块黑铅矿 = models.CharField(verbose_name="块黑铅矿", max_length=32, blank=True, null=True)
    四水锌矾 = models.CharField(verbose_name="四水锌矾", max_length=32, blank=True, null=True)
    硒汞矿 = models.CharField(verbose_name="硒汞矿", max_length=32, blank=True, null=True)
    尖晶石 = models.CharField(verbose_name="尖晶石", max_length=32, blank=True, null=True)
    氮化铝 = models.CharField(verbose_name="氮化铝", max_length=32, blank=True, null=True)
    方镁石 = models.CharField(verbose_name="方镁石", max_length=32, blank=True, null=True)
    铜靛矾 = models.CharField(verbose_name="铜靛矾", max_length=32, blank=True, null=True)
    CuSO4H2O = models.CharField(verbose_name="CuSO4•H2O", max_length=32, blank=True, null=True)
    CdSO30_5H2O = models.CharField(verbose_name="CdSO3•0.5H2O", max_length=32, blank=True, null=True)
    石盐 = models.CharField(verbose_name="石盐", max_length=32, blank=True, null=True)
    氟氯铅矿 = models.CharField(verbose_name="氟氯铅矿", max_length=32, blank=True, null=True)
    铁白云石 = models.CharField(verbose_name="铁白云石", max_length=32, blank=True, null=True)
    钙铝矾 = models.CharField(verbose_name="钙铝矾", max_length=32, blank=True, null=True)
    氯铅矿 = models.CharField(verbose_name="氯铅矿", max_length=32, blank=True, null=True)
    T_B = models.CharField(verbose_name="T B", max_length=32, blank=True, null=True)
    T_Na = models.CharField(verbose_name="T Na", max_length=32, blank=True, null=True)
    T_Mg = models.CharField(verbose_name="T Mg", max_length=32, blank=True, null=True)
    T_Al = models.CharField(verbose_name="T Al", max_length=32, blank=True, null=True)
    T_K = models.CharField(verbose_name="T K", max_length=32, blank=True, null=True)
    T_Ca = models.CharField(verbose_name="T Ca", max_length=32, blank=True, null=True)
    T_Fe = models.CharField(verbose_name="T Fe", max_length=32, blank=True, null=True)
    T_Cu = models.CharField(verbose_name="T Cu", max_length=32, blank=True, null=True)
    T_Pb = models.CharField(verbose_name="T Pb", max_length=32, blank=True, null=True)
    T_Zn = models.CharField(verbose_name="T Zn", max_length=32, blank=True, null=True)
    T_Sn = models.CharField(verbose_name="T Sn", max_length=32, blank=True, null=True)
    T_Ni = models.CharField(verbose_name="T Ni", max_length=32, blank=True, null=True)
    T_Co = models.CharField(verbose_name="T Co", max_length=32, blank=True, null=True)
    T_Sb = models.CharField(verbose_name="T Sb", max_length=32, blank=True, null=True)
    T_Hg = models.CharField(verbose_name="T Hg", max_length=32, blank=True, null=True)
    T_Cd = models.CharField(verbose_name="T Cd", max_length=32, blank=True, null=True)
    T_Bi = models.CharField(verbose_name="T Bi", max_length=32, blank=True, null=True)
    T_Cr = models.CharField(verbose_name="T Cr", max_length=32, blank=True, null=True)
    T_As = models.CharField(verbose_name="T As", max_length=32, blank=True, null=True)
    T_Be = models.CharField(verbose_name="T Be", max_length=32, blank=True, null=True)
    T_Ba = models.CharField(verbose_name="T Ba", max_length=32, blank=True, null=True)
    T_Pd = models.CharField(verbose_name="T Pd", max_length=32, blank=True, null=True)
    T_Pt = models.CharField(verbose_name="T Pt", max_length=32, blank=True, null=True)
    T_V = models.CharField(verbose_name="T V", max_length=32, blank=True, null=True)
    T_Mn = models.CharField(verbose_name="T Mn", max_length=32, blank=True, null=True)
    T_Ti = models.CharField(verbose_name="T Ti", max_length=32, blank=True, null=True)
    T_Al3 = models.CharField(verbose_name="T Al3+", max_length=32, blank=True, null=True)
    T_SO42 = models.CharField(verbose_name="T SO42-", max_length=32, blank=True, null=True)
    CN = models.CharField(verbose_name="CN", max_length=32, blank=True, null=True)
    T_F = models.CharField(verbose_name="T F", max_length=32, blank=True, null=True)
    萘 = models.CharField(verbose_name="萘", max_length=32, blank=True, null=True)
    苊烯 = models.CharField(verbose_name="苊烯", max_length=64, blank=True, null=True)
    苊 = models.CharField(verbose_name="苊", max_length=64, blank=True, null=True)
    芴 = models.CharField(verbose_name="芴", max_length=64, blank=True, null=True)
    菲 = models.CharField(verbose_name="菲", max_length=64, blank=True, null=True)
    蒽 = models.CharField(verbose_name="蒽", max_length=64, blank=True, null=True)
    荧蒽 = models.CharField(verbose_name="荧蒽", max_length=64, blank=True, null=True)
    芘 = models.CharField(verbose_name="芘", max_length=64, blank=True, null=True)
    苯并a蒽 = models.CharField(verbose_name="苯并（a）蒽", max_length=64, blank=True, null=True)
    屈 = models.CharField(verbose_name="屈", max_length=64, blank=True, null=True)
    苯并b荧蒽 = models.CharField(verbose_name="苯并（b）荧蒽", max_length=64, blank=True, null=True)
    苯并k荧蒽 = models.CharField(verbose_name="苯并 (k)荧蒽", max_length=64, blank=True, null=True)
    苯并a芘 = models.CharField(verbose_name="苯并（a）芘", max_length=64, blank=True, null=True)
    茚苯123_cd芘 = models.CharField(verbose_name="茚苯（1,2,3-cd）芘", max_length=64, blank=True, null=True)
    二苯并a_n蒽 = models.CharField(verbose_name=" 二苯并（a, n）蒽", max_length=64, blank=True, null=True)
    苯并ghi北二萘嵌苯 = models.CharField(verbose_name="苯并（ghi）北（二萘嵌苯）", max_length=64, blank=True, null=True)
    乙酸乙酯 = models.CharField(verbose_name="乙酸乙酯", max_length=64, blank=True, null=True)
    乙酸丁酯 = models.CharField(verbose_name="乙酸丁酯", max_length=64, blank=True, null=True)
    乙酸异戊酯 = models.CharField(verbose_name="乙酸异戊酯", max_length=64, blank=True, null=True)
    氨基甲酸乙酯 = models.CharField(verbose_name="氨基甲酸乙酯", max_length=64, blank=True, null=True)
    邻甲酸甲酯 = models.CharField(verbose_name="邻甲酸甲酯", max_length=64, blank=True, null=True)
    邻甲基苯甲酸 = models.CharField(verbose_name="邻甲基苯甲酸", max_length=64, blank=True, null=True)
    丁酸丁酯 = models.CharField(verbose_name="丁酸丁酯", max_length=64, blank=True, null=True)
    N_氰基乙酰亚胺甲酯乙酯 = models.CharField(verbose_name="N-氰基乙酰亚胺甲酯（乙酯）", max_length=64, blank=True, null=True)
    T_43甲基3甲亚基氨基苯基丁酸乙酯 = models.CharField(verbose_name="4-[3-甲基-3-(（甲亚基氨基)）苯基]丁酸乙酯", max_length=64, blank=True, null=True)
    氯甲酸甲酯 = models.CharField(verbose_name="氯甲酸甲酯", max_length=64, blank=True, null=True)
    邻苯二甲酸二甲酯 = models.CharField(verbose_name="邻苯二甲酸二甲酯", max_length=64, blank=True, null=True)
    邻甲基苯甲酸甲酯 = models.CharField(verbose_name="邻甲基苯甲酸甲酯", max_length=64, blank=True, null=True)
    邻苯二甲酸二乙酯 = models.CharField(verbose_name="邻苯二甲酸二乙酯", max_length=64, blank=True, null=True)
    邻苯二甲酸二异丁酯 = models.CharField(verbose_name="邻苯二甲酸二异丁酯", max_length=64, blank=True, null=True)
    邻苯二甲酸二正丁酯 = models.CharField(verbose_name="邻苯二甲酸二正丁酯", max_length=64, blank=True, null=True)
    邻苯二甲酸二2甲氧基乙酯 = models.CharField(verbose_name="邻苯二甲酸二(2-甲氧基)乙酯", max_length=64, blank=True, null=True)
    邻苯二甲酸二4甲基戊基酯 = models.CharField(verbose_name="邻苯二甲酸二(4-甲基-2-戊基)酯", max_length=64, blank=True, null=True)
    邻苯二甲酸二2乙氧基乙酯 = models.CharField(verbose_name="邻苯二甲酸二(2-乙氧基)乙酯", max_length=64, blank=True, null=True)
    邻苯二甲酸二戊酯 = models.CharField(verbose_name="邻苯二甲酸二戊酯", max_length=64, blank=True, null=True)
    邻苯二甲酸二己酯 = models.CharField(verbose_name="邻苯二甲酸二己酯", max_length=64, blank=True, null=True)
    邻苯二甲酸丁基苄基酯 = models.CharField(verbose_name="邻苯二甲酸丁基苄基酯", max_length=64, blank=True, null=True)
    邻苯二甲酸二2丁氧基乙酯 = models.CharField(verbose_name="邻苯二甲酸二(2-丁氧基)乙酯", max_length=64, blank=True, null=True)
    邻苯二甲酸二环己酯 = models.CharField(verbose_name="邻苯二甲酸二环己酯", max_length=64, blank=True, null=True)
    邻苯二甲酸二2乙基己酯 = models.CharField(verbose_name="邻苯二甲酸二（2-乙基）己酯", max_length=64, blank=True, null=True)
    邻苯二甲酸二苯酯 = models.CharField(verbose_name="邻苯二甲酸二苯酯", max_length=64, blank=True, null=True)
    邻苯二甲酸二正辛酯 = models.CharField(verbose_name="邻苯二甲酸二正辛酯", max_length=64, blank=True, null=True)
    邻苯二甲酸二壬酯 = models.CharField(verbose_name="邻苯二甲酸二壬酯", max_length=64, blank=True, null=True)
    苯 = models.CharField(verbose_name="苯", max_length=64, blank=True, null=True)
    甲苯 = models.CharField(verbose_name="甲苯", max_length=64, blank=True, null=True)
    乙苯 = models.CharField(verbose_name="乙苯", max_length=64, blank=True, null=True)
    二甲苯 = models.CharField(verbose_name="二甲苯", max_length=64, blank=True, null=True)
    对二甲苯 = models.CharField(verbose_name="对二甲苯", max_length=64, blank=True, null=True)
    间二甲苯 = models.CharField(verbose_name="间二甲苯", max_length=64, blank=True, null=True)
    邻二甲苯 = models.CharField(verbose_name="邻二甲苯", max_length=64, blank=True, null=True)
    异丙苯 = models.CharField(verbose_name="异丙苯", max_length=64, blank=True, null=True)
    苯乙烯 = models.CharField(verbose_name="苯乙烯", max_length=64, blank=True, null=True)
    乙烯基甲苯 = models.CharField(verbose_name="乙烯基甲苯", max_length=64, blank=True, null=True)
    环己烷 = models.CharField(verbose_name="环己烷", max_length=64, blank=True, null=True)
    二氯甲烷 = models.CharField(verbose_name="二氯甲烷", max_length=64, blank=True, null=True)
    二氯乙烷 = models.CharField(verbose_name="二氯乙烷", max_length=64, blank=True, null=True)
    苯酚 = models.CharField(verbose_name="苯酚", max_length=64, blank=True, null=True)
    邻甲酚 = models.CharField(verbose_name="邻甲酚", max_length=64, blank=True, null=True)
    T_24二氯酚 = models.CharField(verbose_name="2,4-二氯酚", max_length=64, blank=True, null=True)
    T_25二氯苯酚 = models.CharField(verbose_name="2,5-二氯苯酚", max_length=64, blank=True, null=True)
    甲醛  = models.CharField(verbose_name="甲醛", max_length=64, blank=True, null=True)
    间苯氧基苯甲醛 = models.CharField(verbose_name="间苯氧基苯甲醛", max_length=64, blank=True, null=True)
    甲酸  = models.CharField(verbose_name="甲酸", max_length=64, blank=True, null=True)
    苯氧乙酸 = models.CharField(verbose_name="苯氧乙酸", max_length=64, blank=True, null=True)
    氯乙酸 = models.CharField(verbose_name="氯乙酸", max_length=64, blank=True, null=True)
    羟基乙酸 = models.CharField(verbose_name="羟基乙酸", max_length=64, blank=True, null=True)
    T_2甲4氯酸 = models.CharField(verbose_name="2甲4氯酸", max_length=64, blank=True, null=True)
    甘氨酸 = models.CharField(verbose_name="甘氨酸", max_length=64, blank=True, null=True)
    亚磷酸钠 = models.CharField(verbose_name="亚磷酸钠", max_length=64, blank=True, null=True)
    甲基草甘膦酸钠盐 = models.CharField(verbose_name="甲基草甘膦酸钠盐", max_length=64, blank=True, null=True)
    羟甲基磷酸钠盐 = models.CharField(verbose_name="羟甲基磷酸钠盐", max_length=64, blank=True, null=True)
    T_24二氯苯氧乙酸钠 = models.CharField(verbose_name="2,4-二氯苯氧乙酸钠", max_length=64, blank=True, null=True)
    氯甲基吡啶 = models.CharField(verbose_name="氯甲基吡啶", max_length=64, blank=True, null=True)
    吡啶 = models.CharField(verbose_name="吡啶", max_length=64, blank=True, null=True)
    T_2氯5氯甲基吡啶 = models.CharField(verbose_name="2-氯-5-氯甲基吡啶", max_length=64, blank=True, null=True)
    三氯吡啶醇钠 = models.CharField(verbose_name="三氯吡啶醇钠", max_length=64, blank=True, null=True)
    乙基氯化物 = models.CharField(verbose_name="乙基氯化物", max_length=64, blank=True, null=True)
    氯乙酰氯 = models.CharField(verbose_name="氯乙酰氯", max_length=64, blank=True, null=True)
    邻苯二胺 = models.CharField(verbose_name="邻苯二胺", max_length=64, blank=True, null=True)
    苯肼 = models.CharField(verbose_name="苯肼", max_length=64, blank=True, null=True)
    脲 = models.CharField(verbose_name="脲", max_length=64, blank=True, null=True)
    T_1苯基氨基脲 = models.CharField(verbose_name="1-苯基氨基脲", max_length=64, blank=True, null=True)
    二甲胺 = models.CharField(verbose_name="二甲胺", max_length=64, blank=True, null=True)
    T_2氯烟酰胺 = models.CharField(verbose_name="2-氯烟酰胺", max_length=64, blank=True, null=True)
    精胺 = models.CharField(verbose_name="精胺", max_length=64, blank=True, null=True)
    胺醚 = models.CharField(verbose_name="胺醚", max_length=64, blank=True, null=True)
    乙撑硫脲 = models.CharField(verbose_name="乙撑硫脲", max_length=64, blank=True, null=True)
    邻甲基苯基硫脲 = models.CharField(verbose_name="邻甲基苯基硫脲", max_length=64, blank=True, null=True)
    T_2氯N氯甲基_N26二乙基苯基乙酰胺MRM = models.CharField(verbose_name="2-氯-N-(氯甲基)-N-(2,6-二乙基苯基)乙酰胺（MRM）", max_length=64, blank=True, null=True)
    N_26二乙基苯基甲亚胺甲叉 = models.CharField(verbose_name="N-2,6-二乙基苯基甲亚胺（甲叉）", max_length=64, blank=True, null=True)
    丁草胺 = models.CharField(verbose_name="丁草胺", max_length=64, blank=True, null=True)
    T_4_3乙基2甲亚基氨基苯基丁酰氯 = models.CharField(verbose_name="4-[3-乙基-2-(甲亚基氨基)苯基]丁酰氯", max_length=64, blank=True, null=True)
    T_25二氯苯胺 = models.CharField(verbose_name="2,5-二氯苯胺", max_length=64, blank=True, null=True)
    T_24D = models.CharField(verbose_name="2,4-D", max_length=64, blank=True, null=True)
    草甘膦 = models.CharField(verbose_name="草甘膦", max_length=64, blank=True, null=True)
    增甘膦 = models.CharField(verbose_name="增甘膦", max_length=64, blank=True, null=True)
    双甘膦 = models.CharField(verbose_name="双甘膦", max_length=64, blank=True, null=True)
    西玛津 = models.CharField(verbose_name="西玛津", max_length=64, blank=True, null=True)
    三唑磷 = models.CharField(verbose_name="三唑磷", max_length=64, blank=True, null=True)
    烟嘧磺酰氯 = models.CharField(verbose_name="烟嘧磺酰氯", max_length=64, blank=True, null=True)
    烟嘧磺胺 = models.CharField(verbose_name="烟嘧磺胺", max_length=64, blank=True, null=True)
    烟嘧磺隆 = models.CharField(verbose_name="烟嘧磺隆(mg/kg)", max_length=64, blank=True, null=True)
    毒死蜱 = models.CharField(verbose_name="毒死蜱", max_length=64, blank=True, null=True)
    多菌灵 = models.CharField(verbose_name="多菌灵", max_length=64, blank=True, null=True)
    氟乐灵 = models.CharField(verbose_name="氟乐灵", max_length=64, blank=True, null=True)
    # 丁草胺_2 = models.CharField(verbose_name="丁草胺mg/L", max_length=64, blank=True, null=True)
    咪鲜胺 = models.CharField(verbose_name="咪鲜胺", max_length=64, blank=True, null=True)
    莠去津 = models.CharField(verbose_name="莠去津", max_length=64, blank=True, null=True)
    百草枯 = models.CharField(verbose_name="百草枯", max_length=64, blank=True, null=True)
    苯磺隆 = models.CharField(verbose_name="苯磺隆", max_length=64, blank=True, null=True)
    吡虫啉 = models.CharField(verbose_name="吡虫啉", max_length=64, blank=True, null=True)
    咪唑烷 = models.CharField(verbose_name="咪唑（烷）", max_length=64, blank=True, null=True)
    丙环唑 = models.CharField(verbose_name="丙环唑", max_length=64, blank=True, null=True)
    代森锰 = models.CharField(verbose_name="代森锰", max_length=64, blank=True, null=True)
    敌百虫 = models.CharField(verbose_name="敌百虫", max_length=64, blank=True, null=True)
    啶虫脒 = models.CharField(verbose_name="啶虫脒", max_length=64, blank=True, null=True)
    麦草畏 = models.CharField(verbose_name="麦草畏", max_length=64, blank=True, null=True)
    杀虫单 = models.CharField(verbose_name="杀虫单", max_length=64, blank=True, null=True)
    乙草胺 = models.CharField(verbose_name="乙草胺", max_length=64, blank=True, null=True)
    溴丙烷 = models.CharField(verbose_name="溴丙烷", max_length=64, blank=True, null=True)
    四氯化碳 = models.CharField(verbose_name="四氯化碳", max_length=64, blank=True, null=True)
    丙溴磷 = models.CharField(verbose_name="丙溴磷", max_length=64, blank=True, null=True)
    对氯三氟甲苯 = models.CharField(verbose_name="对氯三氟甲苯", max_length=64, blank=True, null=True)
    功夫酰氯 = models.CharField(verbose_name="功夫酰氯", max_length=64, blank=True, null=True)
    苄基三乙基氯化铵 = models.CharField(verbose_name="苄基三乙基氯化铵", max_length=64, blank=True, null=True)
    二氯菊酰氯 = models.CharField(verbose_name="二氯菊酰氯", max_length=64, blank=True, null=True)
    T_4甲基2肼基苯并骈噻唑 = models.CharField(verbose_name="4-甲基-2-肼基苯并骈噻唑", max_length=64, blank=True, null=True)
    苯唑醇 = models.CharField(verbose_name="苯唑醇", max_length=64, blank=True, null=True)
    二甲硫醚 = models.CharField(verbose_name="二甲硫醚", max_length=64, blank=True, null=True)
    硫酸二甲酯 = models.CharField(verbose_name="硫酸二甲酯", max_length=64, blank=True, null=True)
    甲醇 = models.CharField(verbose_name="甲醇", max_length=64, blank=True, null=True)
    乙醇 = models.CharField(verbose_name="乙醇", max_length=64, blank=True, null=True)
    辛硫磷 = models.CharField(verbose_name="辛硫磷", max_length=64, blank=True, null=True)
    T_OO二乙基硫代磷酰氯 = models.CharField(verbose_name="O,O-二乙基硫代磷酰氯", max_length=64, blank=True, null=True)
    # _2氯烟酰胺_2 = models.CharField(verbose_name="P 2-氯烟酰胺", max_length=64, blank=True, null=True)
    # 二氯甲烷_2 = models.CharField(verbose_name="P 二氯甲烷", max_length=64, blank=True, null=True)
    醋酸 = models.CharField(verbose_name="醋酸", max_length=64, blank=True, null=True)
    醋酸酐 = models.CharField(verbose_name="醋酸酐", max_length=64, blank=True, null=True)
    丙烯醛 = models.CharField(verbose_name="丙烯醛", max_length=64, blank=True, null=True)
    丙烯腈 = models.CharField(verbose_name="丙烯腈", max_length=64, blank=True, null=True)
    环戊二烯 = models.CharField(verbose_name="环戊二烯", max_length=64, blank=True, null=True)
    L_Ca = models.CharField(verbose_name="L Ca", max_length=64, blank=True, null=True)
    L_Mg = models.CharField(verbose_name="L Mg", max_length=64, blank=True, null=True)
    L_Fe = models.CharField(verbose_name="L Fe", max_length=64, blank=True, null=True)
    L_Cu = models.CharField(verbose_name="L Cu", max_length=64, blank=True, null=True)
    L_Pb = models.CharField(verbose_name="L Pb", max_length=64, blank=True, null=True)
    L_Zn = models.CharField(verbose_name="L Zn", max_length=64, blank=True, null=True)
    L_Ba = models.CharField(verbose_name="L Ba", max_length=64, blank=True, null=True)
    L_Sn = models.CharField(verbose_name="L Sn ", max_length=64, blank=True, null=True)
    L_Co = models.CharField(verbose_name="L Co", max_length=64, blank=True, null=True)
    L_Sb = models.CharField(verbose_name="L Sb", max_length=64, blank=True, null=True)
    L_Hg = models.CharField(verbose_name="L Hg", max_length=64, blank=True, null=True)
    L_Cd = models.CharField(verbose_name="L Cd", max_length=64, blank=True, null=True)
    L_Bi = models.CharField(verbose_name="L Bi", max_length=64, blank=True, null=True)
    L_Ni = models.CharField(verbose_name="L Ni", max_length=64, blank=True, null=True)
    L_Cr = models.CharField(verbose_name="L Cr", max_length=64, blank=True, null=True)
    L_Ag = models.CharField(verbose_name="L Ag", max_length=64, blank=True, null=True)
    L_As = models.CharField(verbose_name="L As", max_length=64, blank=True, null=True)
    L_Se = models.CharField(verbose_name="L Se", max_length=64, blank=True, null=True)
    L_Br = models.CharField(verbose_name="L Br", max_length=64, blank=True, null=True)
    L_V = models.CharField(verbose_name="L V", max_length=64, blank=True, null=True)
    L_F = models.CharField(verbose_name="L F", max_length=64, blank=True, null=True)

class Admin(models.Model):
    """管理员"""
    username = models.CharField(verbose_name="用户名",max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)
    usertype = models.CharField(verbose_name="用户类型", max_length=64, blank=True, null=True)
    userstate = models.CharField(verbose_name="用户状态", max_length=64, blank=True, null=True)


class WasteImage(models.Model):
    dataId = models.IntegerField(primary_key=True, verbose_name="序号")
    wasteName = models.CharField(verbose_name="固废名称 ", max_length=64, blank=True, null=True)
    img = models.CharField(verbose_name="废物图片 ", max_length=128, blank=True, null=True)






